### ISSUE TITLE
Mapcss key not parsed

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1603]
This rule from unnecessary.mapcss (JOSM)
```css
/* #14256, #15664, #20681 */
way:closed[highway=rest_area][area?],
way:closed[highway=services][area?],
way:closed[aeroway=aerodrome][area?],
way:closed[waterway=riverbank][area?],
way:closed[aeroway=helipad][area?] {
  throwWarning: tr("{0} is unnecessary for {1}", "{2.tag}", "{1.tag}");
  group: tr("unnecessary tag");
  fixRemove: "{2.key}";
}
```
Applied on way https://www.openstreetmap.org/way/926894128 (or https://www.openstreetmap.org/way/98570914 )
```
area	yes 
highway	services 
name	Paterson
```

https://osmose.openstreetmap.fr/nl/issue/fb7bf10b-4376-9a97-5120-4c0a19bec84c
https://osmose.openstreetmap.fr/en/issue/8a03e8a6-2c8e-bc26-3576-e112440580a0
Message: `area=yes is unnecessary for {{1.key}}=services`

`{{1.key}}` should be parsed as `highway`

I don't know if this is a regression of the recent mapcss changes or a preexisting issue
