### ISSUE TITLE
mapcss `[functionresult() <= functionresult()]` gives bad results with numbers

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1882]
[way 680531945](https://www.openstreetmap.org/way/680531945) has the following tags
```
building:levels=11 
building:min_level=9
building:part=yes
```

Having the following mapcss selector from combinations.mapcss in JOSM (where you can temporarily replace `area` by `way` until that PR has been merged)

```css
area[/^(building\|building:part)$/][height =~ /^[0-9]+(\.[0-9]+)?( m)?$/][min_height =~ /^[0-9]+(\.[0-9]+)?( m)?$/][get(split(" ", tag(height)), 0) <= get(split(" ", tag(min_height)), 0)],
area[/^(building\|building:part)$/][building:levels][building:min_level][tag("building:levels") <= tag("building:min_level")] {
throwWarning: tr("{0} is lower or equal to {1} on {2}", "{1.key}", "{2.key}", "{0.key}");
group: tr("suspicious tag combination");
}
```

JOSM will not warn.
Osmose will show the following message:
> building:levels is lower or equal to building:min_level on building:part

So apparently JOSM does a numeric comparison (11 > 9), while Osmose does a string ("11" < "9") comparison for `[tag("building:levels") <= tag("building:min_level")]`

Similar for way 680531956 with `height = 104` and `min_height = 96`.

Maybe we'll have to do some checks with `"value".isdecimal()` or similar in the redefinition of `<=`  (etcetera) in [mapcss_lib.py](https://github.com/osm-fr/osmose-backend/blob/dev/mapcss/mapcss_lib.py#L112).
