### ISSUE TITLE
Different values of phone and of contact:phone (only spaces differ)

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#2341]
item 3092
class 3097
contact:phone=+33 5 56 22 74 03
phone=+33556227403
it's the same value exempt space, it could be usefull to avoit detecting space change

**Comment by Famlam** [comment]
I can see your point here that this warning doesn't benefit much, since it can be interpret without issues in either format and it doesn't point to an actual conflict. Changing the rule to the following would fix this issue.
```css
*[phone][contact:phone][replace(tag("contact:phone"), " ", "")!=replace(tag("phone"), " ", "")],
*[fax][contact:fax][replace(tag("contact:fax"), " ", "")!=replace(tag("fax"), " ", "")],
*[email][contact:email][contact:email!=*email],
*[website][contact:website][contact:website!=*website] {
    group: tr("Different value of tag contact:* and *");
    throwWarning: tr("Different values of {0} and of {1}", "{0.key}", "{1.key}");
    -osmoseItemClassLevel: "3092/3097/2";

    assertMatch: "node phone=1 contact:phone=2";
    assertNoMatch: "node website=1 contact:website=1";
    assertNoMatch: "node phone=\"+31 123 456 789\" contact:phone=\"+31123456789\""
}
```

I didn't do it as a PR, perhaps some people might see issues with "differently-spaced phone numbers" asides from just looking nice
