### ISSUE TITLE
Doc: how to send analysis results to frontend?

### ISSUE THREAD

**Issue by bagage** [osm-fr/osmose-backend#263]
I'm trying to setup osmose locally via docker containers. To simplify it I created a docker-compose file with the following content:

```
version: '2'

services:
  frontend:
    build: osmose-frontend
    ports:
      - "20009:20009"
    environment:
      - OSMOSE_UNLOCKED_UPDATE=on
    networks:
      fixednetwork:
        ipv4_address: 30.6.0.4
  backend:
    volumes:
      - ./osmose-backend/osmose_config_password.py:/opt/osmose-backend/osmose_config_password.py
    build: osmose-backend
    command: --country=comoros
    networks:
      fixednetwork:
        ipv4_address: 30.6.0.5

networks:
  fixednetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 30.6.0.0/16
          gateway: 30.6.0.1
```

And I changed backend config `osmose-backend/modules/config.py` to:

```python
url_frontend_update = "http://30.6.0.4:20009/control/send-update"
```

When I start the containers (`docker-compose up --build -d`, I can see (`docker-compose logs --follow`)  the analysis going on in backend container, but it contains [these logs](https://github.com/osm-fr/osmose-backend/blob/6218adb5a143873b0470987110f1d3881fcb3ef8/osmose_run.py#L638):

> backend_1   | 2018-01-09 18:29:20   code is not correct - won't upload to http://30.6.0.4:20009/control/send-update

I don't want to configure any password (no need for it since it's machine-only network), I'd expect it to work as is but it seems something is missing. Any idea?

**Comment by bagage** [comment]
Thanks to @frodrigo, it's now almost working. Using the following:

docker-compose:
```
version: '2'

services:
  frontend:
    build: osmose-frontend
    ports:
      - "20009:20009"
    environment:
      - OSMOSE_UNLOCKED_UPDATE=on
  backend:
    volumes:
      - ./osmose-backend/osmose_config_password.py:/opt/osmose-backend/osmose_config_password.py
    build: osmose-backend
    command: --country=comoros
```

backend/modules/config.py:
```
url_frontend_update = "http://frontend:20009/control/send-update"
```

osmose_config_password.py:
```
#-*- coding: utf-8 -*-

def set_password(config):
  for country in config.keys(): 
    for k in config[country].analyser.keys():
      config[country].analyser[k] = 'foo'
```

Then you need to open the following URL: http://0.0.0.0:20009/fr/map/#useDevItem=all (*?useDevItem=all* is required!). Also change severity to "all" if needed.

Last issue is that the left menu stays empty (no categories visible). According to @frodrigo and [this](https://github.com/prhod/osmose-vagrant/issues/5), we have to invoke `frontend/tools/menu_update.py` but yet I could not make this part work (the scripting isn't doing anything -- no insert in the DB).
