### ISSUE TITLE
power transformer

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#272]
0. [X] 0. Transforms are always on nodes.

In my opinion, it would be advisable to create a new item dedicated to the transformers, in which one could have several classes:
1. [X] 1. Use of voltage = voltage1; voltage2 instead of voltage: primary = voltage1 + voltage: secondary = voltage2
voltage = * simple is to ban transfos, to avoid lists to; knowing that there are always several tensions involved when it comes to a transformer.
2. [ ] 2. Depending on the voltage values: * one must always find a line power = line or power = cable connected to the transformer with the corresponding value of voltage = *
Example: a transformer equipped with voltgae: primary = 225000 + voltage: secondary = 20000 must have at least two connected lines with voltage = 225000 and voltage = 20000 on.
3. [X] 3. Missing frequency = *
A transformer always operates at a given frequency, it is one of the most important constants in its operation
4. [ ] ~~4. windings must always be equal windings: primary + windings: secondary + windings: tertiary + ... if they are defined (this is far from being the case)
Example: a transformer with only windings = 3 is correct, but if we have windings = 3 + windings: primary = 1, that's wrong.
windings = 3 + windings: primary = 1 + windings: secondary = 2 is right.~~

**Comment by frodrigo** [comment]
0. 
```css
way[power=transformer],
relation[power=transformer] {
    throwWarning: tr("Power Transforms should always be on a node");
    osmoseItemClassLevel: "?/?/2";
    osmoseTag: list("geom", "power");
}
```

1.
```css
node[power=transformer][voltage] {
    throwWarning: tr("On Power Transforms use voltage:primary=* and voltage:secondary=*");
    osmoseItemClassLevel: "?/?/2";
    osmoseTag: list("power");
}
```

2. Require spatial query, TBD.


3.
```css
node[power=transformer][frequency] {
    throwWarning: tr("On Power Transforms define the frequency tag");
    osmoseItemClassLevel: "?/?/3";
    osmoseTag: list("power");

    assertMatch: "node power=transformer";
    assertNoMatch: "node power=transformer frequency=50";
}
```

4. Should be some thing like this, or more complex, but there tow few objects on OSM to deserve an analysis.
```css
node[power=transformer][windings][windings:primary][tag('windings')=tag('windings:primary')+tag('windings:secondary')],
node[power=transformer][windings][windings:secondary][tag('windings')=tag('windings:primary')+tag('windings:secondary')]
 {
    throwWarning: tr("On Power Transforms define the frequency tag");
    osmoseItemClassLevel: "?/?/3";
    osmoseTag: list("power");

    assertNoMatch: "node power=transformer windings=2 windings:primary=1
windings:secondary=1";
    assertMatch: "node power=transformer windings=2 windings:primary=1";
    assertMatch: "node power=transformer windings=2 windings:secondary=1";
}
```

cc @gustavecha
