### ISSUE TITLE
JOSM validator rule [addr:street][addr:place] on Danish addresses

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#559]
@Klumbumbus

This rule alone raise issue on each Danish addresses.

```css
*[addr:street][addr:place] {
  throwWarning: tr("{0} together with {1}", "{0.key}", "{1.key}");
  group: tr("suspicious tag combination");
}
```

https://josm.openstreetmap.de/browser/josm/trunk/data/validator/combinations.mapcss#L280
http://osmose.openstreetmap.fr/en/errors/?source=8864&item=9001&class=9001002
http://osmose.openstreetmap.fr/en/map/#source=8864&item=9001&class=9001002&zoom=15&lat=55.35786&lon=9.19171&level=1%2C2%2C3&tags=&fixable=

@Klumbumbus, if you wish keeping in JOSM I will blacklist it is Osmose.
