### ISSUE TITLE
Rules/FranceSpecificRules (riu)

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#834]
i dont know why, but issues
http://osmose.openstreetmap.fr/en/errors/?item=9019&class=9019001 or
http://osmose.openstreetmap.fr/en/errors/?item=9019&class=9019002
are false.
I can't fix it and I don't understand why it doesn't work with osmose.

perhaps the best solution is to remove it?

**Comment by frodrigo** [comment]
Do you have some example?

**Comment by didier2020** [comment]
missing distance for
http://osmose.openstreetmap.fr/en/errors/?source=411412&item=9019&class=9019001
there is no tag nat_ref on node as the rule

**Comment by frodrigo** [comment]
Problem
```css
node[highway=milestone][operator][nat_ref][!distance][inside("FR")] {
    throwWarning: tr("missing distance");
    group: tr("validation rules highway milestone");
    -osmoseTags: list("ref", "highway");
    -osmoseAssertMatchWithContext: list("node highway=milestone ref=A4 nat_ref=77PR38DC operator=SANEF", "inside=FR");
    -osmoseAssertNoMatchWithContext: list("node highway=milestone ref=A4 distance=38 nat_ref=77PR38DC operator=SANEF", "inside=FR");
}
```

match

|k|v||
|-- | -- | --
|ele | 67.0 |  
|highway | milestone |  
|note | Please do not move. |  
|operator | CD84 |  
|ref | 8 |  
|ref:highway | D12 |  
|road:separated | no |  
|side | left |  
|source:url | http://www.crige-paca.org/geoportail/geocatalogue.html
