### ISSUE TITLE
Mapcss: remove only part of rule

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#987]
When missing class, only remove the part of the rule requiring it.

```css
relation[type=multipolygon] >[role="inner"] way[area][eval(number_of_tags()) = 1] {
  throwWarning: tr("{0} on an inner multipolygon ring without further tags", "{0.tag}");
  fixRemove: "area";
  set area_yes_autofix;
  group: tr("suspicious tag combination");
}

*[lanes][eval(number_of_tags()) = 1],
*[surface][eval(number_of_tags()) = 1],
*[access][eval(number_of_tags()) = 1],
*[area][eval(number_of_tags()) = 1]!.area_yes_autofix,
*[name][eval(number_of_tags()) = 1],
*[ref][eval(number_of_tags()) = 1],
*[lit][eval(number_of_tags()) = 1] {
  throwWarning: tr("incomplete object: only {0}", "{0.key}");
  set only_one_tag;
  group: tr("missing tag");
}
```
